import AuthProvider from "@/contexts/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactQueryProvider } from "@/contexts/ReactQueryProvider";
import Providers from "@/Providers";
import { GlobalContextProvider } from "@/contexts/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <AuthProvider>
          <body className={inter.className}>
            <GlobalContextProvider>
             <Providers>
               {children}
             </Providers>
            </GlobalContextProvider>
          </body>
        </AuthProvider>
      </ReactQueryProvider>
    </html>
  );
}
